name: isoimagewriter

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v4.3.0
        with:
          target: 'desktop'
          host: 'windows'
          install-deps: 'true'
          modules: 'all'

      - name: Setup MSVC environment
        uses: seanmiddleditch/gha-setup-vsdevenv@master
        with:
          arch: 'x64'
          

      - name: Configure Release
        run: |
          Invoke-WebRequest 'https://raw.githubusercontent.com/KDE/craft/master/setup/install_craft.ps1' -OutFile install_craft.ps1
          powershell -ExecutionPolicy Bypass -File .\install_craft.ps1 -root "C:\CraftRoot" --use-defaults

      - name: Build
        run: |
          dir C:\CraftRoot\
          C:\hostedtoolcache\windows\Python\3.12.10\x64\python.exe C:\CraftRoot\craft-tmp\bin\craft.py craft
          C:\CraftRoot\craft\craftenv.ps1
          cd "D:/a/isoimagewriter/isoimagewriter"
          
          C:\hostedtoolcache\windows\Python\3.12.10\x64\python.exe C:\CraftRoot\craft-tmp\bin\craft.py --help
          C:\hostedtoolcache\windows\Python\3.12.10\x64\python.exe C:\CraftRoot\craft-tmp\bin\craft.py --add-blueprint-repository https://invent.kde.org/packaging/craft-blueprints-kde.git
          C:\hostedtoolcache\windows\Python\3.12.10\x64\python.exe C:\CraftRoot\craft-tmp\bin\craft.py -i isoimagewriter 
          C:\hostedtoolcache\windows\Python\3.12.10\x64\python.exe C:\CraftRoot\craft-tmp\bin\craft.py  --package --target=25.08.0 isoimagewriter

